// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthenticationClient is the client API for Authentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthenticationClient interface {
	ReqPG(ctx context.Context, in *ReqPGRequest, opts ...grpc.CallOption) (*ReqPGResponse, error)
	ReqDHParams(ctx context.Context, in *ReqDHParamsRequest, opts ...grpc.CallOption) (*ReqDHParamsResponse, error)
}

type authenticationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationClient(cc grpc.ClientConnInterface) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) ReqPG(ctx context.Context, in *ReqPGRequest, opts ...grpc.CallOption) (*ReqPGResponse, error) {
	out := new(ReqPGResponse)
	err := c.cc.Invoke(ctx, "/auth.Authentication/ReqPG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) ReqDHParams(ctx context.Context, in *ReqDHParamsRequest, opts ...grpc.CallOption) (*ReqDHParamsResponse, error) {
	out := new(ReqDHParamsResponse)
	err := c.cc.Invoke(ctx, "/auth.Authentication/ReqDHParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServer is the server API for Authentication service.
// All implementations must embed UnimplementedAuthenticationServer
// for forward compatibility
type AuthenticationServer interface {
	ReqPG(context.Context, *ReqPGRequest) (*ReqPGResponse, error)
	ReqDHParams(context.Context, *ReqDHParamsRequest) (*ReqDHParamsResponse, error)
	mustEmbedUnimplementedAuthenticationServer()
}

// UnimplementedAuthenticationServer must be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServer struct {
}

func (UnimplementedAuthenticationServer) ReqPG(context.Context, *ReqPGRequest) (*ReqPGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqPG not implemented")
}
func (UnimplementedAuthenticationServer) ReqDHParams(context.Context, *ReqDHParamsRequest) (*ReqDHParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqDHParams not implemented")
}
func (UnimplementedAuthenticationServer) mustEmbedUnimplementedAuthenticationServer() {}

// UnsafeAuthenticationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthenticationServer will
// result in compilation errors.
type UnsafeAuthenticationServer interface {
	mustEmbedUnimplementedAuthenticationServer()
}

func RegisterAuthenticationServer(s grpc.ServiceRegistrar, srv AuthenticationServer) {
	s.RegisterService(&Authentication_ServiceDesc, srv)
}

func _Authentication_ReqPG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).ReqPG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authentication/ReqPG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).ReqPG(ctx, req.(*ReqPGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_ReqDHParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqDHParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).ReqDHParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Authentication/ReqDHParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).ReqDHParams(ctx, req.(*ReqDHParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authentication_ServiceDesc is the grpc.ServiceDesc for Authentication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authentication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqPG",
			Handler:    _Authentication_ReqPG_Handler,
		},
		{
			MethodName: "ReqDHParams",
			Handler:    _Authentication_ReqDHParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
